engines:
    phpmd:
        enabled: true
        config:
            file_extensions: "php"

    phpcodesniffer:
        enabled: true
        config:
            file_extensions: "php"

    duplication:
        enabled: true
        config:
            languages:
                - php:

ratings:
    paths:
        - "src/**.php"

exclude_paths:
    - "test/**"
    - "vendor/**"
