version: "3"
services:
    cli:
        image: anax/dev:cli
        volumes: [ ".:/home/anax/repo" ]
    web:
        image: anax/dev:apache
        volumes: [ ".:/home/anax/repo" ]
        ports: [ "10099:80" ]
